# Generated by Django 6.0.2 on 2026-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_equipment_image_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
