# Generated by Django 6.0.2 on 2026-03-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction Equipment'), ('party', 'Party & Event Equipment'), ('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('clothing', 'Clothing & Fashion')], max_length=50),
        ),
    ]
