# Generated by Django 6.0.2 on 2026-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
