# Generated by Django 6.0.2 on 2026-04-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_booking_damage_description_booking_damage_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gcash_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='gcash_receipts/'),
        ),
    ]
