# Generated by Django 6.0.2 on 2026-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_booking_gcash_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gcash_receipt',
        ),
        migrations.AddField(
            model_name='booking',
            name='gcash_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
