# Generated by Django 6.0.2 on 2026-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_gcash_receipt_booking_gcash_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='equipment',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty per 3 hours overdue', max_digits=10),
        ),
    ]
