# Generated by Django 6.0.2 on 2026-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_extension_reason_equipment_penalty_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
